# Site settings
title: David Camargo
subtitle: Human Oriented engineer
email: davidcp90@gmail.com
description: I want to bring peace between technology and people. They are made for each other, and I was made to make that dream come true.
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost" # the base hostname & protocol for your site
author:

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 10

# Social settings
500px_url:
facebook_url:
github_url: http://github.com/davidcp90
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://co.linkedin.com/in/davidhumanengineer
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass